version: '3.8'

services:
  db:
    image: postgres:14
    container_name: clinicas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinicas_api
    ports:
      - "4200:4200"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/clinicas
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      # Monta somente a pasta de código-fonte para evitar sobrescrever node_modules
      - ./src:/app/src:ro

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
