version: '3.8'

services:
  db:
    image: postgres:14
    container_name: clinicas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: clinicas_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/clinicas

volumes:
  pgdata:

networks:
  app-network:
